#spring.application.name=dine-in-order
spring:
  application:
    name: dine-in-order-api

  datasource:
    url: jdbc:mysql://localhost:3306/dine_in_orderdb?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
    ddl-auto: update